#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebsiteGameStore_Fix")]
	public partial class dbQLBanGameDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblChiTietDonHang(tblChiTietDonHang instance);
    partial void UpdatetblChiTietDonHang(tblChiTietDonHang instance);
    partial void DeletetblChiTietDonHang(tblChiTietDonHang instance);
    partial void InserttblTinTuc(tblTinTuc instance);
    partial void UpdatetblTinTuc(tblTinTuc instance);
    partial void DeletetblTinTuc(tblTinTuc instance);
    partial void InserttblDonDatHang(tblDonDatHang instance);
    partial void UpdatetblDonDatHang(tblDonDatHang instance);
    partial void DeletetblDonDatHang(tblDonDatHang instance);
    partial void InserttblDonHang(tblDonHang instance);
    partial void UpdatetblDonHang(tblDonHang instance);
    partial void DeletetblDonHang(tblDonHang instance);
    partial void InserttblKhacHang(tblKhacHang instance);
    partial void UpdatetblKhacHang(tblKhacHang instance);
    partial void DeletetblKhacHang(tblKhacHang instance);
    partial void InserttblLoaiSanPham(tblLoaiSanPham instance);
    partial void UpdatetblLoaiSanPham(tblLoaiSanPham instance);
    partial void DeletetblLoaiSanPham(tblLoaiSanPham instance);
    partial void InserttblLoaiTaiKhoan(tblLoaiTaiKhoan instance);
    partial void UpdatetblLoaiTaiKhoan(tblLoaiTaiKhoan instance);
    partial void DeletetblLoaiTaiKhoan(tblLoaiTaiKhoan instance);
    partial void InserttblNhaCungCap(tblNhaCungCap instance);
    partial void UpdatetblNhaCungCap(tblNhaCungCap instance);
    partial void DeletetblNhaCungCap(tblNhaCungCap instance);
    partial void InserttblPhieuGiaoHang(tblPhieuGiaoHang instance);
    partial void UpdatetblPhieuGiaoHang(tblPhieuGiaoHang instance);
    partial void DeletetblPhieuGiaoHang(tblPhieuGiaoHang instance);
    partial void InserttblSanPham(tblSanPham instance);
    partial void UpdatetblSanPham(tblSanPham instance);
    partial void DeletetblSanPham(tblSanPham instance);
    partial void InserttblTaiKhoan(tblTaiKhoan instance);
    partial void UpdatetblTaiKhoan(tblTaiKhoan instance);
    partial void DeletetblTaiKhoan(tblTaiKhoan instance);
    partial void InserttblThuongHieu(tblThuongHieu instance);
    partial void UpdatetblThuongHieu(tblThuongHieu instance);
    partial void DeletetblThuongHieu(tblThuongHieu instance);
    #endregion
		
		public dbQLBanGameDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebsiteGameStore_FixConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanGameDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanGameDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanGameDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLBanGameDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblChiTietDonHang> tblChiTietDonHangs
		{
			get
			{
				return this.GetTable<tblChiTietDonHang>();
			}
		}
		
		public System.Data.Linq.Table<tblTinTuc> tblTinTucs
		{
			get
			{
				return this.GetTable<tblTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<tblDonDatHang> tblDonDatHangs
		{
			get
			{
				return this.GetTable<tblDonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<tblDonHang> tblDonHangs
		{
			get
			{
				return this.GetTable<tblDonHang>();
			}
		}
		
		public System.Data.Linq.Table<tblKhacHang> tblKhacHangs
		{
			get
			{
				return this.GetTable<tblKhacHang>();
			}
		}
		
		public System.Data.Linq.Table<tblLoaiSanPham> tblLoaiSanPhams
		{
			get
			{
				return this.GetTable<tblLoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tblLoaiTaiKhoan> tblLoaiTaiKhoans
		{
			get
			{
				return this.GetTable<tblLoaiTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<tblNhaCungCap> tblNhaCungCaps
		{
			get
			{
				return this.GetTable<tblNhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<tblPhieuGiaoHang> tblPhieuGiaoHangs
		{
			get
			{
				return this.GetTable<tblPhieuGiaoHang>();
			}
		}
		
		public System.Data.Linq.Table<tblSanPham> tblSanPhams
		{
			get
			{
				return this.GetTable<tblSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this.GetTable<tblTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<tblThuongHieu> tblThuongHieus
		{
			get
			{
				return this.GetTable<tblThuongHieu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietDonHang")]
	public partial class tblChiTietDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _MaDH;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _DonGia;
		
		private string _MaKH;
		
		private EntityRef<tblDonHang> _tblDonHang;
		
		private EntityRef<tblSanPham> _tblSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnMaDHChanging(string value);
    partial void OnMaDHChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    #endregion
		
		public tblChiTietDonHang()
		{
			this._tblDonHang = default(EntityRef<tblDonHang>);
			this._tblSanPham = default(EntityRef<tblSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._tblSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					if (this._tblDonHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tblDonHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDonHang_tblChiTietDonHang", Storage="_tblDonHang", ThisKey="MaDH,MaKH", OtherKey="MaDH,MaKH", IsForeignKey=true)]
		public tblDonHang tblDonHang
		{
			get
			{
				return this._tblDonHang.Entity;
			}
			set
			{
				tblDonHang previousValue = this._tblDonHang.Entity;
				if (((previousValue != value) 
							|| (this._tblDonHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDonHang.Entity = null;
						previousValue.tblChiTietDonHangs.Remove(this);
					}
					this._tblDonHang.Entity = value;
					if ((value != null))
					{
						value.tblChiTietDonHangs.Add(this);
						this._MaDH = value.MaDH;
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaDH = default(string);
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("tblDonHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblChiTietDonHang", Storage="_tblSanPham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public tblSanPham tblSanPham
		{
			get
			{
				return this._tblSanPham.Entity;
			}
			set
			{
				tblSanPham previousValue = this._tblSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSanPham.Entity = null;
						previousValue.tblChiTietDonHangs.Remove(this);
					}
					this._tblSanPham.Entity = value;
					if ((value != null))
					{
						value.tblChiTietDonHangs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(string);
					}
					this.SendPropertyChanged("tblSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTinTuc")]
	public partial class tblTinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTT;
		
		private string _TieuDeTT;
		
		private string _NoiDung;
		
		private string _Username;
		
		private EntityRef<tblTaiKhoan> _tblTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnTieuDeTTChanging(string value);
    partial void OnTieuDeTTChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
		
		public tblTinTuc()
		{
			this._tblTaiKhoan = default(EntityRef<tblTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeTT", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TieuDeTT
		{
			get
			{
				return this._TieuDeTT;
			}
			set
			{
				if ((this._TieuDeTT != value))
				{
					this.OnTieuDeTTChanging(value);
					this.SendPropertyChanging();
					this._TieuDeTT = value;
					this.SendPropertyChanged("TieuDeTT");
					this.OnTieuDeTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._tblTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTaiKhoan_tblTinTuc", Storage="_tblTaiKhoan", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public tblTaiKhoan tblTaiKhoan
		{
			get
			{
				return this._tblTaiKhoan.Entity;
			}
			set
			{
				tblTaiKhoan previousValue = this._tblTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tblTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTaiKhoan.Entity = null;
						previousValue.tblTinTucs.Remove(this);
					}
					this._tblTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tblTinTucs.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("tblTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDonDatHang")]
	public partial class tblDonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDDH;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private string _MaNCC;
		
		private EntitySet<tblPhieuGiaoHang> _tblPhieuGiaoHangs;
		
		private EntityRef<tblNhaCungCap> _tblNhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDDHChanging(string value);
    partial void OnMaDDHChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    #endregion
		
		public tblDonDatHang()
		{
			this._tblPhieuGiaoHangs = new EntitySet<tblPhieuGiaoHang>(new Action<tblPhieuGiaoHang>(this.attach_tblPhieuGiaoHangs), new Action<tblPhieuGiaoHang>(this.detach_tblPhieuGiaoHangs));
			this._tblNhaCungCap = default(EntityRef<tblNhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDDH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDDH
		{
			get
			{
				return this._MaDDH;
			}
			set
			{
				if ((this._MaDDH != value))
				{
					this.OnMaDDHChanging(value);
					this.SendPropertyChanging();
					this._MaDDH = value;
					this.SendPropertyChanged("MaDDH");
					this.OnMaDDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tblNhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDonDatHang_tblPhieuGiaoHang", Storage="_tblPhieuGiaoHangs", ThisKey="MaDDH,MaNCC", OtherKey="MaDDH,MaNCC")]
		public EntitySet<tblPhieuGiaoHang> tblPhieuGiaoHangs
		{
			get
			{
				return this._tblPhieuGiaoHangs;
			}
			set
			{
				this._tblPhieuGiaoHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblDonDatHang", Storage="_tblNhaCungCap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public tblNhaCungCap tblNhaCungCap
		{
			get
			{
				return this._tblNhaCungCap.Entity;
			}
			set
			{
				tblNhaCungCap previousValue = this._tblNhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tblNhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhaCungCap.Entity = null;
						previousValue.tblDonDatHangs.Remove(this);
					}
					this._tblNhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tblDonDatHangs.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tblNhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuGiaoHangs(tblPhieuGiaoHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDonDatHang = this;
		}
		
		private void detach_tblPhieuGiaoHangs(tblPhieuGiaoHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDonDatHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDonHang")]
	public partial class tblDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDH;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<System.DateTime> _NgayGiao;
		
		private System.Nullable<bool> _Dathanhtoan;
		
		private System.Nullable<bool> _TinhTrangGiaoHang;
		
		private string _Username;
		
		private string _MaKH;
		
		private EntitySet<tblChiTietDonHang> _tblChiTietDonHangs;
		
		private EntityRef<tblKhacHang> _tblKhacHang;
		
		private EntityRef<tblTaiKhoan> _tblTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDHChanging(string value);
    partial void OnMaDHChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnNgayGiaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoChanged();
    partial void OnDathanhtoanChanging(System.Nullable<bool> value);
    partial void OnDathanhtoanChanged();
    partial void OnTinhTrangGiaoHangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangGiaoHangChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    #endregion
		
		public tblDonHang()
		{
			this._tblChiTietDonHangs = new EntitySet<tblChiTietDonHang>(new Action<tblChiTietDonHang>(this.attach_tblChiTietDonHangs), new Action<tblChiTietDonHang>(this.detach_tblChiTietDonHangs));
			this._tblKhacHang = default(EntityRef<tblKhacHang>);
			this._tblTaiKhoan = default(EntityRef<tblTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDH
		{
			get
			{
				return this._MaDH;
			}
			set
			{
				if ((this._MaDH != value))
				{
					this.OnMaDHChanging(value);
					this.SendPropertyChanging();
					this._MaDH = value;
					this.SendPropertyChanged("MaDH");
					this.OnMaDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiao
		{
			get
			{
				return this._NgayGiao;
			}
			set
			{
				if ((this._NgayGiao != value))
				{
					this.OnNgayGiaoChanging(value);
					this.SendPropertyChanging();
					this._NgayGiao = value;
					this.SendPropertyChanged("NgayGiao");
					this.OnNgayGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dathanhtoan", DbType="Bit")]
		public System.Nullable<bool> Dathanhtoan
		{
			get
			{
				return this._Dathanhtoan;
			}
			set
			{
				if ((this._Dathanhtoan != value))
				{
					this.OnDathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Dathanhtoan = value;
					this.SendPropertyChanged("Dathanhtoan");
					this.OnDathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangGiaoHang", DbType="Bit")]
		public System.Nullable<bool> TinhTrangGiaoHang
		{
			get
			{
				return this._TinhTrangGiaoHang;
			}
			set
			{
				if ((this._TinhTrangGiaoHang != value))
				{
					this.OnTinhTrangGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangGiaoHang = value;
					this.SendPropertyChanged("TinhTrangGiaoHang");
					this.OnTinhTrangGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(30)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._tblTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tblKhacHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDonHang_tblChiTietDonHang", Storage="_tblChiTietDonHangs", ThisKey="MaDH,MaKH", OtherKey="MaDH,MaKH")]
		public EntitySet<tblChiTietDonHang> tblChiTietDonHangs
		{
			get
			{
				return this._tblChiTietDonHangs;
			}
			set
			{
				this._tblChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhacHang_tblDonHang", Storage="_tblKhacHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tblKhacHang tblKhacHang
		{
			get
			{
				return this._tblKhacHang.Entity;
			}
			set
			{
				tblKhacHang previousValue = this._tblKhacHang.Entity;
				if (((previousValue != value) 
							|| (this._tblKhacHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhacHang.Entity = null;
						previousValue.tblDonHangs.Remove(this);
					}
					this._tblKhacHang.Entity = value;
					if ((value != null))
					{
						value.tblDonHangs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("tblKhacHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTaiKhoan_tblDonHang", Storage="_tblTaiKhoan", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public tblTaiKhoan tblTaiKhoan
		{
			get
			{
				return this._tblTaiKhoan.Entity;
			}
			set
			{
				tblTaiKhoan previousValue = this._tblTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tblTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTaiKhoan.Entity = null;
						previousValue.tblDonHangs.Remove(this);
					}
					this._tblTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tblDonHangs.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("tblTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDonHang = this;
		}
		
		private void detach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblDonHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKhacHang")]
	public partial class tblKhacHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _Username;
		
		private string _Password;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<tblDonHang> _tblDonHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public tblKhacHang()
		{
			this._tblDonHangs = new EntitySet<tblDonHang>(new Action<tblDonHang>(this.attach_tblDonHangs), new Action<tblDonHang>(this.detach_tblDonHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhacHang_tblDonHang", Storage="_tblDonHangs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tblDonHang> tblDonHangs
		{
			get
			{
				return this._tblDonHangs;
			}
			set
			{
				this._tblDonHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDonHangs(tblDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblKhacHang = this;
		}
		
		private void detach_tblDonHangs(tblDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblKhacHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoaiSanPham")]
	public partial class tblLoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public tblLoaiSanPham()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiSanPham_tblSanPham", Storage="_tblSanPhams", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiSanPham = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoaiTaiKhoan")]
	public partial class tblLoaiTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiTK;
		
		private string _ChucVu;
		
		private EntitySet<tblTaiKhoan> _tblTaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiTKChanging(string value);
    partial void OnMaLoaiTKChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public tblLoaiTaiKhoan()
		{
			this._tblTaiKhoans = new EntitySet<tblTaiKhoan>(new Action<tblTaiKhoan>(this.attach_tblTaiKhoans), new Action<tblTaiKhoan>(this.detach_tblTaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTK", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiTK
		{
			get
			{
				return this._MaLoaiTK;
			}
			set
			{
				if ((this._MaLoaiTK != value))
				{
					this.OnMaLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTK = value;
					this.SendPropertyChanged("MaLoaiTK");
					this.OnMaLoaiTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiTaiKhoan_tblTaiKhoan", Storage="_tblTaiKhoans", ThisKey="MaLoaiTK", OtherKey="MaLoaiTK")]
		public EntitySet<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this._tblTaiKhoans;
			}
			set
			{
				this._tblTaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiTaiKhoan = this;
		}
		
		private void detach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiTaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhaCungCap")]
	public partial class tblNhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<tblDonDatHang> _tblDonDatHangs;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public tblNhaCungCap()
		{
			this._tblDonDatHangs = new EntitySet<tblDonDatHang>(new Action<tblDonDatHang>(this.attach_tblDonDatHangs), new Action<tblDonDatHang>(this.detach_tblDonDatHangs));
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblDonDatHang", Storage="_tblDonDatHangs", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<tblDonDatHang> tblDonDatHangs
		{
			get
			{
				return this._tblDonDatHangs;
			}
			set
			{
				this._tblDonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblSanPham", Storage="_tblSanPhams", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDonDatHangs(tblDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = this;
		}
		
		private void detach_tblDonDatHangs(tblDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = null;
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhieuGiaoHang")]
	public partial class tblPhieuGiaoHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPGH;
		
		private System.Nullable<System.DateTime> _NgayGiao;
		
		private string _MaDDH;
		
		private string _MaNCC;
		
		private EntityRef<tblDonDatHang> _tblDonDatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPGHChanging(string value);
    partial void OnMaPGHChanged();
    partial void OnNgayGiaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoChanged();
    partial void OnMaDDHChanging(string value);
    partial void OnMaDDHChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    #endregion
		
		public tblPhieuGiaoHang()
		{
			this._tblDonDatHang = default(EntityRef<tblDonDatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPGH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPGH
		{
			get
			{
				return this._MaPGH;
			}
			set
			{
				if ((this._MaPGH != value))
				{
					this.OnMaPGHChanging(value);
					this.SendPropertyChanging();
					this._MaPGH = value;
					this.SendPropertyChanged("MaPGH");
					this.OnMaPGHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiao
		{
			get
			{
				return this._NgayGiao;
			}
			set
			{
				if ((this._NgayGiao != value))
				{
					this.OnNgayGiaoChanging(value);
					this.SendPropertyChanging();
					this._NgayGiao = value;
					this.SendPropertyChanged("NgayGiao");
					this.OnNgayGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDDH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDDH
		{
			get
			{
				return this._MaDDH;
			}
			set
			{
				if ((this._MaDDH != value))
				{
					if (this._tblDonDatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDDHChanging(value);
					this.SendPropertyChanging();
					this._MaDDH = value;
					this.SendPropertyChanged("MaDDH");
					this.OnMaDDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tblDonDatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDonDatHang_tblPhieuGiaoHang", Storage="_tblDonDatHang", ThisKey="MaDDH,MaNCC", OtherKey="MaDDH,MaNCC", IsForeignKey=true)]
		public tblDonDatHang tblDonDatHang
		{
			get
			{
				return this._tblDonDatHang.Entity;
			}
			set
			{
				tblDonDatHang previousValue = this._tblDonDatHang.Entity;
				if (((previousValue != value) 
							|| (this._tblDonDatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDonDatHang.Entity = null;
						previousValue.tblPhieuGiaoHangs.Remove(this);
					}
					this._tblDonDatHang.Entity = value;
					if ((value != null))
					{
						value.tblPhieuGiaoHangs.Add(this);
						this._MaDDH = value.MaDDH;
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaDDH = default(string);
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tblDonDatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSanPham")]
	public partial class tblSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _TenSP;
		
		private System.Nullable<decimal> _GiaTien;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private string _HinhAnh;
		
		private string _MoTa;
		
		private string _MaNCC;
		
		private string _MaTH;
		
		private string _MaLoai;
		
		private EntitySet<tblChiTietDonHang> _tblChiTietDonHangs;
		
		private EntityRef<tblNhaCungCap> _tblNhaCungCap;
		
		private EntityRef<tblLoaiSanPham> _tblLoaiSanPham;
		
		private EntityRef<tblThuongHieu> _tblThuongHieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnMaTHChanging(string value);
    partial void OnMaTHChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    #endregion
		
		public tblSanPham()
		{
			this._tblChiTietDonHangs = new EntitySet<tblChiTietDonHang>(new Action<tblChiTietDonHang>(this.attach_tblChiTietDonHangs), new Action<tblChiTietDonHang>(this.detach_tblChiTietDonHangs));
			this._tblNhaCungCap = default(EntityRef<tblNhaCungCap>);
			this._tblLoaiSanPham = default(EntityRef<tblLoaiSanPham>);
			this._tblThuongHieu = default(EntityRef<tblThuongHieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(100)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="Char(5)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tblNhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTH", DbType="Char(5)")]
		public string MaTH
		{
			get
			{
				return this._MaTH;
			}
			set
			{
				if ((this._MaTH != value))
				{
					if (this._tblThuongHieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTHChanging(value);
					this.SendPropertyChanging();
					this._MaTH = value;
					this.SendPropertyChanged("MaTH");
					this.OnMaTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Char(5)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._tblLoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSanPham_tblChiTietDonHang", Storage="_tblChiTietDonHangs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<tblChiTietDonHang> tblChiTietDonHangs
		{
			get
			{
				return this._tblChiTietDonHangs;
			}
			set
			{
				this._tblChiTietDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblSanPham", Storage="_tblNhaCungCap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public tblNhaCungCap tblNhaCungCap
		{
			get
			{
				return this._tblNhaCungCap.Entity;
			}
			set
			{
				tblNhaCungCap previousValue = this._tblNhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tblNhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhaCungCap.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblNhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tblNhaCungCap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiSanPham_tblSanPham", Storage="_tblLoaiSanPham", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public tblLoaiSanPham tblLoaiSanPham
		{
			get
			{
				return this._tblLoaiSanPham.Entity;
			}
			set
			{
				tblLoaiSanPham previousValue = this._tblLoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tblLoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLoaiSanPham.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblLoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("tblLoaiSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThuongHieu_tblSanPham", Storage="_tblThuongHieu", ThisKey="MaTH", OtherKey="MaTH", IsForeignKey=true)]
		public tblThuongHieu tblThuongHieu
		{
			get
			{
				return this._tblThuongHieu.Entity;
			}
			set
			{
				tblThuongHieu previousValue = this._tblThuongHieu.Entity;
				if (((previousValue != value) 
							|| (this._tblThuongHieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblThuongHieu.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblThuongHieu.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaTH = value.MaTH;
					}
					else
					{
						this._MaTH = default(string);
					}
					this.SendPropertyChanged("tblThuongHieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = this;
		}
		
		private void detach_tblChiTietDonHangs(tblChiTietDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTaiKhoan")]
	public partial class tblTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private string _MaLoaiTK;
		
		private EntitySet<tblTinTuc> _tblTinTucs;
		
		private EntitySet<tblDonHang> _tblDonHangs;
		
		private EntityRef<tblLoaiTaiKhoan> _tblLoaiTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnMaLoaiTKChanging(string value);
    partial void OnMaLoaiTKChanged();
    #endregion
		
		public tblTaiKhoan()
		{
			this._tblTinTucs = new EntitySet<tblTinTuc>(new Action<tblTinTuc>(this.attach_tblTinTucs), new Action<tblTinTuc>(this.detach_tblTinTucs));
			this._tblDonHangs = new EntitySet<tblDonHang>(new Action<tblDonHang>(this.attach_tblDonHangs), new Action<tblDonHang>(this.detach_tblDonHangs));
			this._tblLoaiTaiKhoan = default(EntityRef<tblLoaiTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiTK", DbType="Char(5)")]
		public string MaLoaiTK
		{
			get
			{
				return this._MaLoaiTK;
			}
			set
			{
				if ((this._MaLoaiTK != value))
				{
					if (this._tblLoaiTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiTK = value;
					this.SendPropertyChanged("MaLoaiTK");
					this.OnMaLoaiTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTaiKhoan_tblTinTuc", Storage="_tblTinTucs", ThisKey="Username", OtherKey="Username")]
		public EntitySet<tblTinTuc> tblTinTucs
		{
			get
			{
				return this._tblTinTucs;
			}
			set
			{
				this._tblTinTucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTaiKhoan_tblDonHang", Storage="_tblDonHangs", ThisKey="Username", OtherKey="Username")]
		public EntitySet<tblDonHang> tblDonHangs
		{
			get
			{
				return this._tblDonHangs;
			}
			set
			{
				this._tblDonHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiTaiKhoan_tblTaiKhoan", Storage="_tblLoaiTaiKhoan", ThisKey="MaLoaiTK", OtherKey="MaLoaiTK", IsForeignKey=true)]
		public tblLoaiTaiKhoan tblLoaiTaiKhoan
		{
			get
			{
				return this._tblLoaiTaiKhoan.Entity;
			}
			set
			{
				tblLoaiTaiKhoan previousValue = this._tblLoaiTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._tblLoaiTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLoaiTaiKhoan.Entity = null;
						previousValue.tblTaiKhoans.Remove(this);
					}
					this._tblLoaiTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.tblTaiKhoans.Add(this);
						this._MaLoaiTK = value.MaLoaiTK;
					}
					else
					{
						this._MaLoaiTK = default(string);
					}
					this.SendPropertyChanged("tblLoaiTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTinTucs(tblTinTuc entity)
		{
			this.SendPropertyChanging();
			entity.tblTaiKhoan = this;
		}
		
		private void detach_tblTinTucs(tblTinTuc entity)
		{
			this.SendPropertyChanging();
			entity.tblTaiKhoan = null;
		}
		
		private void attach_tblDonHangs(tblDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblTaiKhoan = this;
		}
		
		private void detach_tblDonHangs(tblDonHang entity)
		{
			this.SendPropertyChanging();
			entity.tblTaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblThuongHieu")]
	public partial class tblThuongHieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTH;
		
		private string _TenTH;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTHChanging(string value);
    partial void OnMaTHChanged();
    partial void OnTenTHChanging(string value);
    partial void OnTenTHChanged();
    #endregion
		
		public tblThuongHieu()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTH
		{
			get
			{
				return this._MaTH;
			}
			set
			{
				if ((this._MaTH != value))
				{
					this.OnMaTHChanging(value);
					this.SendPropertyChanging();
					this._MaTH = value;
					this.SendPropertyChanged("MaTH");
					this.OnMaTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTH", DbType="NVarChar(50)")]
		public string TenTH
		{
			get
			{
				return this._TenTH;
			}
			set
			{
				if ((this._TenTH != value))
				{
					this.OnTenTHChanging(value);
					this.SendPropertyChanging();
					this._TenTH = value;
					this.SendPropertyChanged("TenTH");
					this.OnTenTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThuongHieu_tblSanPham", Storage="_tblSanPhams", ThisKey="MaTH", OtherKey="MaTH")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblThuongHieu = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblThuongHieu = null;
		}
	}
}
#pragma warning restore 1591
